### ISSUE TITLE
I can spend any amount of tokens

### ISSUE THREAD

**Issue by mezrin** [Dexaran/ERC23-tokens#5]
https://github.com/Dexaran/ERC23-tokens/blob/ERC20_compatible/ERC23_token.sol#L69

Where is the check of balances? I can spend any amount of tokens. It is terribly
Where are your unit-tests ?

**Comment by Dexaran** [comment]
It's not a bug because of it's not related to token standard. The things you are talking about are part of the implementation.

I want to standardize contract functions and transaction handling method. Also I want to keep the example code clean from the code that is not associated with the token standard. I didn't said that this should be implemented as-is.

This checks, SafeMath library and whatever else things that you want are details of implementation.

**Comment by Dexaran** [comment]
As far as I know there is no such checks in ERC20 example also.
